language: node_js
node_js:
  - "6.9.2"
addons:
  firefox: "latest"
before_install:
  - ./build/travis/init-env
  - ./build/travis/install-geckodriver
  - ./build/travis/start-xvfb
  - . ./build/travis/env.sh
  - export DISPLAY=$ENV_DISPLAY
  - export PATH=$PATH:$ENV_LOCAL_BIN_DIR
install:
  - npm install --global gulp-cli
  - npm run bootstrap
script:
  - gulp unit-test-with-coverage
  - gulp dist
  - gulp start-server
  - gulp acceptance-test
  - gulp stop-server
  - gulp lint
  - gulp docs
after_script:
  - gulp publish-coverage
