language: node_js
node_js:
    - "0.10"
install:
    - npm install -g cucumber
    - npm install -g jasmine
    - npm install -g jison
    - npm install -g jscs
    - npm install -g jsdoc
    - npm install -g jshint
    - npm install
script:
    - make all
    - make start-app
    - make acceptance-test
    - make stop-app

