language: node_js
node_js:
    - "4.2.1"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - make init
script:
    - make unit-test-with-coverage
    - make dist
    - make start-server
    - make acceptance-test
    - make stop-server
    - make check
    - make docs
after_script:
    - make publish-coverage

