language: node_js
node_js:
    - "0.10"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - npm install -g cucumber
    - npm install -g istanbul
    - npm install -g jasmine
    - npm install -g jison
    - npm install -g jscs
    - npm install -g jsdoc
    - npm install -g jshint
    - npm install
script:
    - make all
    - make start-app
    - make acceptance-test
    - make stop-app
    - make docs
    - make coverage
after_script:
    - make publish-coverage

