language: node_js
node_js:
  - "6.9.1"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - npm install --global gulp-cli
  - make init
script:
  - gulp unit-test-with-coverage
#  - make dist
#  - make start-server
#  - make acceptance-test
#  - make stop-server
  - gulp check
  - gulp docs
after_script:
  - gulp publish-coverage
