language: node_js
node_js:
    - "4.2.1"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - npm install
script:
    - make all
    - make start-server
    - make acceptance-test
    - make stop-server
    - make docs
    - make coverage
after_script:
    - make publish-coverage

