dist: trusty
sudo: false
language: node_js
node_js:
  - "6.9.2"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  firefox: "latest"
before_install:
  - ./tools/travis/init-env
  - ./tools/travis/install-chromedriver
  - ./tools/travis/install-geckodriver
  - ./tools/travis/start-xvfb
  - . ./tools/travis/env.sh
  - export DISPLAY=$ENV_DISPLAY
  - export PATH=$PATH:$ENV_LOCAL_BIN_DIR
install:
  - npm install --global gulp-cli
  - npm run bootstrap
script:
  - gulp unit-test-with-coverage
  - gulp dist
  - gulp start-server
  - gulp acceptance-test:server
  - ENV_WEBDRIVER_BROWSER_NAME=phantomjs gulp acceptance-test:client
  - ENV_WEBDRIVER_BROWSER_NAME=chrome gulp acceptance-test:client
  - ENV_WEBDRIVER_BROWSER_NAME=firefox gulp acceptance-test:client
  - gulp stop-server
  - gulp lint
  - gulp docs
after_script:
  - gulp publish-coverage
