language: node_js
node_js:
  - "6.9.1"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mkdir -p .local/bin
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz -O /tmp/geckodriver.tar.gz
  - tar xzf /tmp/geckodriver.tar.gz -C $PWD/.local/bin
  - export PATH=$PATH:$PWD/.local/bin
install:
  - npm install --global gulp-cli
  - npm install
  - npm run init
script:
  - gulp unit-test-with-coverage
  - gulp dist
  - gulp start-server
  - gulp acceptance-test
  - gulp stop-server
  - gulp check
  - gulp docs
after_script:
  - gulp publish-coverage
