# Matrix of pentagonal trapezohedron vertex coordinates (see
# http://www.georgehart.com/virtual-polyhedra/vrml/pentagonal_trapezohedron.wrl).
vertices_3d = matrix(
  c(
     0.5257311,  0.381966,  0.8506508,    # (x1, y1, z1)
    -0.2008114,  0.618034,  0.8506508,
    -0.6498394,  0,         0.8506508,
     0.5257311, -1.618034,  0.8506508,
     1.051462,   0,        -0.2008114,
     0.8506508,  0.618034,  0.2008114,
    -0.5257311,  1.618034, -0.8506508,
    -1.051462,   0,         0.2008114,
    -0.8506508, -0.618034, -0.2008114,
     0.2008114, -0.618034, -0.8506508,
     0.6498394,  0,        -0.8506508,
    -0.5257311, -0.381966, -0.8506508     # (x12, y12, z12)
  ),
  nrow=3,
  ncol=12
)

# Rotate die to generate 2D view from above while it is at rest on a surface
# (the above vertex coordinates were [arbitrarily?] generated by the author
# at an angle of 18 degrees off the x-axis).
angle = 18 * pi / 180
rotate_z_neg_angle = matrix(
  c(
    cos(-angle), -sin(-angle), 0,
    sin(-angle),  cos(-angle), 0,
    0,            0,           1
  ),
  nrow=3,
  ncol=3,
  byrow=TRUE
)
vertices_3d_rot = rotate_z_neg_angle %*% vertices_3d

# Extract 2D vertex coordinates and order them in such a way to optimize
# drawing.  The 2D vertices are as labeled below.  (**) represents the origin.
#
#                 ( 4)                          +--> x
#                                               |
#  ( 9)                          ( 5)           V
#                                               y
#                 (**)
#       ( 3)                ( 2)
#  ( 8)                          ( 6)
#                 ( 1)
#
#                 ( 7)
#
vertices_2d = matrix(
  c(
    vertices_3d_rot[1, 2], vertices_3d_rot[2, 2],     # (x'1, y'1)
    vertices_3d_rot[1, 1], vertices_3d_rot[2, 1],
    vertices_3d_rot[1, 3], vertices_3d_rot[2, 3],
    vertices_3d_rot[1, 4], vertices_3d_rot[2, 4],
    vertices_3d_rot[1, 5], vertices_3d_rot[2, 5],
    vertices_3d_rot[1, 6], vertices_3d_rot[2, 6],
    vertices_3d_rot[1, 7], vertices_3d_rot[2, 7],
    vertices_3d_rot[1, 8], vertices_3d_rot[2, 8],
    vertices_3d_rot[1, 9], vertices_3d_rot[2, 9]      # (x'9, y'9)
  ),
  nrow=2,
  ncol=9
)
